name: ktlint and detekt

on:
  push:
    branches: ['main']
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Detekt & KtLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Prepare Android environment
        uses: ./.github/actions/prepare-android
        with:
          free-disk-space: 'false'
          run-yarn-build: 'false'

      - name: Restore Gradle cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        working-directory: gradle-plugins/react
        run: ./gradlew :brownfield:detekt --no-daemon --stacktrace

      - name: Run KtLint
        working-directory: gradle-plugins/react
        run: ./gradlew :brownfield:ktlintCheck --no-daemon --stacktrace
